# Generated by Django 2.2.4 on 2019-09-01 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190901_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_membership',
            name='cart_item',
        ),
        migrations.RemoveField(
            model_name='s_membership',
            name='cart_item',
        ),
    ]
